### ISSUE TITLE
Implement search capability for entire site.

### ISSUE THREAD

**Issue by mkoai** [QuiteStochastic/cs373-idb#56]
Description from project page:

Create a search capability.
The result of a search must be a list of links to crises and/or organizations and/or people (e.g. like Google).
The search results must be contextualized and the search terms must show up.
The search results must be clickable.
Multi-word search must show clearly marked and results followed by or results.

**Comment by tvarney** [comment]
So this looks like it is not per-pillar, but a general search. That makes things a bit more interesting, since we need to mark the matches in some way (bold, like google?). For relevance, we should be searching the name first, then the description. Bonus would be to search the relations for matches such that searching for "jeoffry" would return all things he was linked to.

**Comment by tvarney** [comment]
Closed as of latest commit; custom search engine written using a series of queries on each pillar. Results within a category (exact, fuzzy, and, or) are ordered arbitrarily.
